return {
	-- "luckasRanarison/tailwind-tools.nvim",
	-- dependencies = { "nvim-treesitter/nvim-treesitter" },
	-- opts = {
	-- 	custom_filetypes = { "angular", "angular.html" }, -- see the extension section to learn how it works
	-- }, -- your configuration
	-- {
	-- 	"hrsh7th/nvim-cmp",
	--
	-- 	-- event = "InsertEnter",
	-- 	dependencies = {
	-- 		{ "roobert/tailwindcss-colorizer-cmp.nvim", config = true },
	-- 	},
	-- 	opts = function(_, opts)
	-- 		-- original LazyVim kind icon formatter
	-- 		local format_kinds = opts.formatting.format
	-- 		opts.formatting.format = function(entry, item)
	-- 			format_kinds(entry, item) -- add icons
	-- 			return require("tailwindcss-colorizer-cmp").formatter(entry, item)
	-- 		end
	-- 	end,
	-- },
}
